spring:
  datasource:
    url: jdbc:mysql://root:EEdVhlBtijLGSYbhFCQtOhTwYKuifRRQ@ballast.proxy.rlwy.net:46922/railway
    driver-class-name: com.mysql.cj.jdbc.Driver
website-url: http://localhost:8080