spring:
  datasource:
    url: jdbc:mysql://caboose.proxy.rlwy.net:12981/railway
    username: root
    password: rkoZyfOeSmpTDOLwELWfYLflwdAXlDyk

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600
  refresh-token-expiration: 604800

stripe:
#  api-key: ${STRIPE_API_KEY}
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET_KEY}

website-url: http://localhost:8080