spring:
  datasource:
    url: jdbc:mysql://root:EEdVhlBtijLGSYbhFCQtOhTwYKuifRRQ@ballast.proxy.rlwy.net:46922/railway
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600
  refresh-token-expiration: 604800

stripe:
#  api-key: ${STRIPE_API_KEY}
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET_KEY}

website-url: http://localhost:8080